// fsModes.drift.test.ts — Wiring Integrity Audit, item (d).
// Run: npx tsx src/lib/config/fsModes.drift.test.ts
//
// fsModes.ts's MODE_COST (the frontend's single source of truth for what the
// UI displays/prices) and games/future_spinner/library/publish_files/index.json
// (the shipped maths package's actual per-mode cost, independently generated by
// the optimiser) currently agree exactly. Nothing previously guarded that
// agreement, so a future tier added to one side without the other would drift
// silently - a live-mode/served-mode mismatch of exactly the kind the buy-tier
// billing bug was. This test fails loudly if they ever disagree, or if either
// side lists a mode the other doesn't know about.

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { FS_MODES } from './fsModes.ts'

const here = dirname(fileURLToPath(import.meta.url))
const indexPath = resolve(here, '../../../../games/future_spinner/library/publish_files/index.json')
const index: { modes: Array<{ name: string; cost: number }> } = JSON.parse(readFileSync(indexPath, 'utf-8'))

let pass = 0
const failures: string[] = []

const indexByServerMode = new Map(index.modes.map((m) => [m.name, m.cost]))
const fsModesByServerMode = new Map(FS_MODES.map((m) => [m.serverMode, m.cost]))

for (const m of FS_MODES) {
  const label = `${m.id} (serverMode ${m.serverMode})`
  if (!indexByServerMode.has(m.serverMode)) {
    failures.push(`${label}: fsModes.ts declares it, but index.json has no "${m.serverMode}" mode entry at all`)
    continue
  }
  const shippedCost = indexByServerMode.get(m.serverMode)!
  if (shippedCost !== m.cost) {
    failures.push(`${label}: fsModes.ts cost ${m.cost}x != index.json shipped cost ${shippedCost}x`)
    continue
  }
  pass++
}

for (const shipped of index.modes) {
  if (!fsModesByServerMode.has(shipped.name)) {
    failures.push(`index.json has a shipped "${shipped.name}" mode (cost ${shipped.cost}x) with no matching fsModes.ts entry - the frontend cannot price or serve it`)
  }
}

console.log('='.repeat(70))
console.log('FSMODES / INDEX.JSON DRIFT GATE')
console.log('='.repeat(70))
console.log(`fsModes.ts modes: ${FS_MODES.length}  index.json modes: ${index.modes.length}  matched: ${pass}`)
if (failures.length) {
  console.log('')
  console.log('FAILURES:')
  for (const f of failures) console.log('  - ' + f)
  console.log('')
  console.log('DRIFT GATE: FAIL')
  process.exitCode = 1
} else {
  console.log('')
  console.log('DRIFT GATE: PASS (fsModes.ts and the shipped index.json agree exactly, mode for mode)')
}
