#!/usr/bin/env python3
"""Flame-jet sprite generator (Opus elevate 2, Task 1).

Exports from design-system/masters/M3_master_v3.svg (the Plasma Booster) two
things, deterministically, for the Overdrive frame-edge jets:
  - jet_nozzle.png        the nozzle assembly (barrel + mouth), tight viewBox.
  - jet_flame_sheet.png   a 5-frame horizontal sprite strip of the flame,
                          generated by parametrically varying the flame group
                          scale and the core-path opacity in the SVG before
                          rasterising (a CSS steps() sprite loop drives it, so
                          no per-frame allocation in the engine).
  - jet_flame_static.png  a single static-glow frame for prefers-reduced-motion.

Run via `npm run assets` (chained after build.py) or directly:
    scripts/assets/.venv/bin/python scripts/assets/flame_jets.py
"""
import xml.etree.ElementTree as ET
from pathlib import Path

import cairosvg
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "design-system/masters/M3_master_v3.svg"
OUT = ROOT / "frontend/public/assets/themes/future-spinner/ui"
TMP = Path(__file__).resolve().parent / ".jet_tmp"
NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", NS)

FRAME_W, FRAME_H = 240, 120
FLAME_VB = "452 392 520 260"     # nozzle mouth to spark tips
NOZZLE_VB = "296 356 312 312"
# per-frame (scale_x, scale_y, core_opacity_factor) — a hand-tuned flicker:
# brief flare then settle, never a linear ramp.
FRAMES = [
    (0.90, 0.94, 0.72),
    (1.00, 1.00, 0.95),
    (1.09, 1.06, 0.82),
    (1.02, 0.98, 1.00),
    (0.94, 0.96, 0.80),
]


def local(el):
    return el.tag.split("}")[-1]


def keep_only(root, keep_id):
    for child in list(root):
        if local(child) == "defs":
            continue
        if child.get("id") == keep_id:
            continue
        root.remove(child)


def set_view(root, vb, w, h):
    root.set("viewBox", vb)
    root.set("width", str(w))
    root.set("height", str(h))


def render(root, out, w, h):
    out.parent.mkdir(parents=True, exist_ok=True)
    cairosvg.svg2png(bytestring=ET.tostring(root, encoding="utf-8"),
                     write_to=str(out), output_width=w, output_height=h)


def main():
    if not SRC.exists():
        raise SystemExit(f"source not found: {SRC}")
    TMP.mkdir(parents=True, exist_ok=True)

    # nozzle assembly
    tree = ET.parse(SRC); root = tree.getroot()
    keep_only(root, "jetNozzle")
    set_view(root, NOZZLE_VB, 160, 160)
    render(root, OUT / "jet_nozzle.png", 160, 160)

    # flame frames -> sprite sheet
    frames = []
    for i, (sx, sy, co) in enumerate(FRAMES):
        tree = ET.parse(SRC); root = tree.getroot()
        keep_only(root, "jetFlame")
        flame = root.find(f".//{{{NS}}}g[@id='jetFlame']")
        flame.set("transform", f"translate(452 512) scale({sx} {sy}) translate(-452 -512)")
        core = root.find(f".//{{{NS}}}path[@id='flameCore']")
        if core is not None:
            core.set("opacity", f"{round(0.95 * co, 3)}")
        set_view(root, FLAME_VB, FRAME_W, FRAME_H)
        tmp = TMP / f"f{i}.png"
        render(root, tmp, FRAME_W, FRAME_H)
        frames.append(Image.open(tmp).convert("RGBA"))

    sheet = Image.new("RGBA", (FRAME_W * len(frames), FRAME_H), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        sheet.alpha_composite(f, (i * FRAME_W, 0))
    sheet.save(OUT / "jet_flame_sheet.png", "PNG")

    # static-glow variant for prefers-reduced-motion (the settled frame)
    frames[3].save(OUT / "jet_flame_static.png", "PNG")

    for p in TMP.glob("*.png"):
        p.unlink()
    TMP.rmdir()
    print(f"flame jets -> {OUT.relative_to(ROOT)}: jet_nozzle.png, "
          f"jet_flame_sheet.png ({len(frames)} frames {FRAME_W}x{FRAME_H}), jet_flame_static.png")


if __name__ == "__main__":
    main()
